version: '3.8'

volumes:
  pg-data:
  mongo-data:

services:
  postgres:
    image: postgres:12.7-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  app:
    build: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DB_PASSWORD=postgres
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - postgres

  proxy:
    image: nginx:1.11
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/main/resources/static:/data/static/

  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}

  mongo:
    image: mongo:5.0.3-focal
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/var/lib/mongo/data